name    'jhoblitt-sysstat'
version '1.0.0'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-sysstat'
source 'https://github.com/jhoblitt/puppet-sysstat.git'
summary 'manage the sysstat package'
description 'manage the sysstat package'
dependency 'puppetlabs/stdlib', '>= 1.0.0'
